
/**
 * This class can be used to generate hashes 
 *
 */
import java.util.Scanner; 
import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class Test {
	
	public static byte[] getSHA(String input) throws NoSuchAlgorithmException {
        // Static getInstance method is called with hashing SHA
        MessageDigest md = MessageDigest.getInstance("SHA-256");
 
        // digest() method called
        // to calculate message digest of an input
        // and return array of byte
        return md.digest(input.getBytes(StandardCharsets.UTF_8));
 }
 
 public static String toHexString(byte[] hash){
        // Convert byte array into signum representation
        BigInteger number = new BigInteger(1, hash);
 
        // Convert message digest into hex value
        StringBuilder hexString = new StringBuilder(number.toString(16));
 
        // Pad with leading zeros
        while (hexString.length() < 64)
        {
            hexString.insert(0, '0');
        }
 
        return hexString.toString();
  }
     
	
	public static void main(String[] args) throws NoSuchAlgorithmException {

		Scanner input = new Scanner(System.in);
		
		
		
		System.out.println("Select an action: ");
		System.out.println("-------------------");
		System.out.println("1. Generate Hash");
		System.out.println("2. Compare Hash");
		System.out.println("3. Re-compute");	
		System.out.println("-------------------");
		 
		System.out.println("Your Action is: ");
		System.out.println("-------------------");
		int actionNum = input.nextInt(); 
		
		if (actionNum==1) {
			System.out.println("1. Generate Hash");
		}
		else if (actionNum==2) {
			System.out.println("2. Compare Hash");
		}
		else {
			System.out.println("3. Re-compute");
		}
		
		
		
		System.out.println("-------------------");
		System.out.println("HashCode Generated by SHA-256 for:");
		System.out.println("-------------------");
		String hash  = new Scanner(System.in).nextLine(); 
		System.out.println("\n" + hash + " : " + toHexString(getSHA(hash)));
		
		
	}
	
	 
}
